{
    'name': 'FCS Route Planner',
    'version': '17.0.1.0.0',
    'summary': 'Planificador de rutas de reparto para FCS Flores Cristo de la Sed',
    'author': 'FCS',
    'category': 'Operations/Delivery',
    'depends': ['base', 'mail', 'web', 'control_stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/delivery_zone_data.xml',
        'data/funeral_home_data.xml',
        'data/demo_vehicle_data.xml',
        'views/delivery_zone_views.xml',
        'views/delivery_vehicle_views.xml',
        'views/funeral_home_views.xml',
        'views/delivery_order_views.xml',
        'views/delivery_route_views.xml',
        'views/route_planning_wizard_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
